PierreIdentity/Models/Treat.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace PierreIdentity.Models
{
  public class Treat
  {
    public Treat()
    {
      this.TreatFlavors = new HashSet<TreatFlavor>();
    }
    public int TreatId { get; set; }
    [Required]
    public string Name { get; set; }
    public virtual ICollection<TreatFlavor> TreatFlavors { get;}
    public virtual ApplicationUser User { get; set; }
  }
}

PierreIdentity/ViewModels/AddFlavorViewModel.cs
using PierreIdentity.Models;
using System.Collections.Generic;

namespace PierreIdentity.ViewModels
{
  public class AddFlavorViewModel
  {
    public Treat Treat { get; set; }
    public IEnumerable<SelectFlavorViewModel> Flavors { get; set; }
  }
}

PierreIdentity/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierreIdentity.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreIdentity.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierreIdentityContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierreIdentityContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index ()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.TreatFlavors)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    } 

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }


}

PierreIdentity/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierreIdentity.Models;
using PierreIdentity.ViewModels;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;


namespace PierreIdentity.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierreIdentityContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierreIdentityContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index ()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.TreatFlavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    } 

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      var viewModel = new AddFlavorViewModel 
      {
        Treat = treat,
        Flavors = _db.Flavors.Select(flavor => new SelectFlavorViewModel 
        { 
          FlavorId = flavor.FlavorId, 
          Name = flavor.Name, 
          IsSelected = _db.TreatFlavors.Where(entry => entry.TreatId == id).Any(entry => entry.FlavorId == flavor.FlavorId)
          }).ToList()
      };
    
      return View(viewModel);
    }

    [HttpPost]
    public ActionResult AddFlavor(AddFlavorViewModel viewModel, int id)
    {
      if (viewModel.Flavors.Any())
      {
        foreach(var selectedFlavor in viewModel.Flavors.Where(flavor => flavor.IsSelected))
        {
          if(!_db.TreatFlavors.Where(entry => entry.TreatId == viewModel.Treat.TreatId).Any(entry => entry.FlavorId == selectedFlavor.FlavorId))
          {
          _db.TreatFlavors.Add(new TreatFlavor() { TreatId = viewModel.Treat.TreatId, FlavorId = selectedFlavor.FlavorId
            });
          }
        }
        foreach(var selectedFlavor in viewModel.Flavors.Where(flavor => !flavor.IsSelected))
        {
          var thisTreatFlavor = _db.TreatFlavors.Where(entry => entry.TreatId == viewModel.Treat.TreatId).FirstOrDefault(entry => entry.FlavorId == selectedFlavor.FlavorId);
          if(_db.TreatFlavors.Where(entry => entry.TreatId == viewModel.Treat.TreatId).Any(entry => entry.FlavorId == selectedFlavor.FlavorId))
          {
          // _db.TreatFlavors.Add(new TreatFlavor() { TreatId = viewModel.Treat.TreatId, FlavorId = selectedFlavor.FlavorId});
          _db.TreatFlavors.Remove(thisTreatFlavor);
          }
        _db.SaveChanges();
        }
      }
      return RedirectToAction("Details", new { id = id });
      
    }
  }


}

PierreIdentity/Views/Treats/AddFlavor.cshtml
@using PierreIdentity.ViewModels
@model AddFlavorViewModel

<h1>add flavor to @Html.DisplayFor(model => model.Treat.Name)</h1>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.Treat.TreatId)

  @Html.Label("Select flavors")
  @Html.EditorFor(model => model.Flavors)
  <input type="submit" value="Save" />
}

PierreIdentity/Views/Treats/Create.cshtml
@model PierreIdentity.Models.Treat
<h4>Create new treat</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  
  <input type="submit" value="Create Treat" class="btn btn-primary">
}

PierreIdentity/Views/Treats/Delete.cshtml
@model PierreIdentity.Models.Treat

<h2>Would you like to delete @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<div class="subnav">
  <p>@Html.ActionLink("Back To Treats", "Index")</p>
</div>

PierreIdentity/Views/Treats/Details.cshtml
@using System.Security.Claims
@model PierreIdentity.Models.Treat

@if(User.Identity.IsAuthenticated)
{
<nav class="subnav">
  <p>@Html.ActionLink("Add flavor", "AddFlavor", new { id = Model.TreatId})</p>
  <p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId})</p>
  <p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId})</p>
</nav>
}

<h3>@Html.DisplayFor(model => model.Name)</h3>

@if(@Model.TreatFlavors.Any())
{
  <ul>
    @foreach(var treatFlavor in Model.TreatFlavors)
    {
      <li>@Html.ActionLink(@treatFlavor.Flavor.Name, "Details", "Flavors", new { id = @treatFlavor.Flavor.FlavorId})</li>

    }
  </ul>
}

PierreIdentity/Views/Treats/Edit.cshtml
@model PierreIdentity.Models.Treat

<h2>Edit @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="save" class="btn btn-success" />
}

<div class="subnav">
  <p>@Html.ActionLink("Back To Treats", "Index")</p>
</div>

PierreIdentity/Views/Treats/Index.cshtml
@using PierreIdentity.Models;
@using System.Security.Claims
@model IEnumerable<PierreIdentity.Models.Treat>
@if(User.Identity.IsAuthenticated)
{
<div class="subnav">
  <p>@Html.ActionLink("Create new Treat", "Create")</p>
</div>
}

<h1>Treats</h1>

@if(Model.Any())
{
  <ul>
    @foreach(Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}
else
{
  <p>Nothing added yet</p>
}